<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputPath>/home/mox/Projects/VSmods/vsmodding/arrowsnslings/compiled</OutputPath>
    <AssemblyName>arrowsnslings</AssemblyName>
    <RootNamespace>arrowsnslings</RootNamespace>
  </PropertyGroup>

 <ItemGroup>

     <!-- Core  -->
    <Reference Include="Vintagestory">
      <HintPath>/home/mox/.config/VSLGameVersions/1.22.3/Vintagestory.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <!-- Core API -->
    <Reference Include="VintagestoryAPI">
      <HintPath>/home/mox/.config/VSLGameVersions/1.22.3/VintagestoryAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <!-- Game systems (ItemStone, etc.) -->
    <Reference Include="VSSurvivalMod">
      <HintPath>/home/mox/.config/VSLGameVersions/1.22.3/Mods/VSSurvivalMod.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <!-- Projectiles, combat, etc. -->
    <Reference Include="VSEssentials">
      <HintPath>/home/mox/.config/VSLGameVersions/1.22.3/Mods/VSEssentials.dll</HintPath>
      <Private>false</Private>
    </Reference>

  </ItemGroup>


  <ItemGroup>
    <Content Include="assets\**">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="modinfo.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
